name: Auto commit

on:

  push:
    branches:
      - main
   
   
  schedule:
  - cron: "0 */6 * * *"

jobs:
  auto_commit:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3      
        with:
         ref: "main"
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "globs-loucas0w@icloud.com"
          git config --local user.name "Igor Alves"
          git add -A
          
          arr[0]="chore: 🤖 auto commit"
          arr[1]="chore: 🟩 auto commit"
          arr[2]="chore: 👻 auto commit"
          arr[3]="chore: 🦄 auto commit"
          arr[4]="chore: 🦴 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
