name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Waka Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_TIME: false
          CODE_LANG: typescript
          BLOCKS: ->
          STOP_AT_OTHER: true
          LANG_COUNT: 3
          IGNORED_LANGUAGES: YAML JSON TOM Bash
